//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.TADD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "Ma User")]
        public int ID { get; set; }
        [Required(ErrorMessage = "Name not empty...")]
        [Display(Name = "Ten User")]
        public string NameUser { get; set; }
        [DisplayName("Vi tri")]
        public string RoleUser { get; set; }
        [DisplayName("Nhap Mat Khau")]
        [Required(ErrorMessage = "Password not empty...")]
        public string PasswordUser { get; set; }
        [NotMapped]
        [Compare("PasswordUser")]
        [DisplayName("Nhap Lai Mat Khau")]
        public string Confirmpass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}