//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.TADD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayOrder
    {
        public int Id { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public string Day { get; set; }
        public int SL { get; set; }
        public virtual Product Product { get; set; }
    }
}
